/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF, useAnimations, MeshTransmissionMaterial, Html , Image } from "@react-three/drei";

export default function Counter(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF("/models/counter.glb");
  const { actions } = useAnimations(animations, group);
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <mesh
          name="Center"
          castShadow
          receiveShadow
          geometry={nodes.Center.geometry}
          material={nodes.Center.material}
        />
        <mesh
          name="Sphere"
          castShadow
          receiveShadow
          geometry={nodes.Sphere.geometry}
     
        //   material={}
        >
            <MeshTransmissionMaterial
            distortionScale={0}
            temporalDistortion={0}
            samples={16}
            resolution={512}
            anisotropy={1}
            thickness={0.1}
            roughness={0}
            toneMapped={true}
            color={'mediumpurple'}
            />
        </mesh>
        <Image
            position={[0, 1.6, -3.8]}
            scale={[1.2, 1.2]}
            url="/images/counter-bg.png"
            transparent
            toneMapped={false}
        />
<Html transform position={[0, 1.6, -3.8]} rotation={[0,0,0]} >
            <div className="counter" >
                <div className="counter-number">0</div>
            </div>
        </Html>
      </group>
    </group>
  );
}

useGLTF.preload("/models/counter.glb");
