/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

export default function Rings(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF("/models/rings.glb");
  const { actions } = useAnimations(animations, group);
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <mesh
          name="OuterRing"
          castShadow
          receiveShadow
          geometry={nodes.OuterRing.geometry}
          material={materials["Material.003"]}
        />
        <mesh
          name="OuterRing001"
          castShadow
          receiveShadow
          geometry={nodes.OuterRing001.geometry}
          material={materials["Material.001"]}
        />
        <mesh
          name="OuterRing002"
          castShadow
          receiveShadow
          geometry={nodes.OuterRing002.geometry}
          material={materials["Material.003"]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/models/rings.glb");
